name: game_keeper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  # routing
  auto_route: ^7.9.0
  # http client
  retrofit: ^4.1.0
  # state management
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  # dependency injection
  get_it: ^7.6.7
  injectable: ^2.3.5
  # json serialization
  json_annotation: ^4.8.1
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  # animations
  lottie: ^3.1.0
  # google fonts
  google_fonts: ^6.2.1
  # local storage
  hive: ^4.0.0-dev.2
  shared_preferences: ^2.2.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  # google sign in
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.9
  # dots indicator
  smooth_page_indicator: ^1.1.0
  easy_localization: ^3.0.5
  firebase_core: ^2.27.1
  # monet color A12+
  dynamic_color: ^1.7.0
  # flutter screen util
  flutter_screenutil: ^5.9.0
  # flutter font awesome
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.5.1
  #flutter_test:
  # sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/translations/

  
