name: game_keeper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_route: ^7.9.0
  bloc: ^8.1.3
  fast_cached_network_image: ^1.2.8
  dio: ^5.4.1
  dynamic_color: ^1.7.0
  easy_localization: ^3.0.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  injectable: ^2.3.5
  isar_flutter_libs: ^4.0.0-dev.13
  json_annotation: ^4.8.1
  loader_overlay: ^4.0.0
  lottie: ^3.1.0
  path_provider: ^2.1.0
  retrofit: ^4.1.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  #flutter_test:
  # sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  injectable_generator: ^2.5.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    #- assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/translations/
