name: game_keeper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_route: ^7.9.0
  retrofit: ^4.1.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  injectable: ^2.3.5
  json_annotation: ^4.8.1
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.5.1
  #flutter_test:
  # sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
