// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5I6_Qch-TVkrFdPDTIAAYmvFINsnuus',
    appId: '1:948317348123:android:7b3debf162f6d5f3e433be',
    messagingSenderId: '948317348123',
    projectId: 'game-keeper-9a86e',
    storageBucket: 'game-keeper-9a86e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfsVeCvC0ourN2xouOaNlD77s0tEQ7l34',
    appId: '1:948317348123:ios:37b329ef17def667e433be',
    messagingSenderId: '948317348123',
    projectId: 'game-keeper-9a86e',
    storageBucket: 'game-keeper-9a86e.appspot.com',
    androidClientId: '948317348123-l2juplpc1mfvlrdabn7qfcjma92k09qh.apps.googleusercontent.com',
    iosClientId: '948317348123-h2pqoqtqvp008m1vtpp6ts15142phlko.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameKeeper',
  );
}
